/**
 * M6 logo ingest — build src/fixtures/cologne-logos.json from ByMykel.
 *
 * VERIFY, DON'T ASSUME (handoff DoD): the spec pointed at
 *   https://bymykel.github.io/CSGO-API/api/en/stickers.json
 * which is DEAD (301 → 404 GitHub-Pages "File not found", checked 2026-05-24).
 * The API relocated to raw.githubusercontent.com — confirmed by ByMykel's own
 * docs page (BASE URL: raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/{lang}).
 * SOURCE_URL below is the live one; re-run this script to refresh the manifest.
 *
 * What it does: pulls the full sticker list, keeps type:Team + the Cologne
 * event + the plain (effect:"Other") variant, then maps each of the layout's
 * teams to a sticker image. Two match keys, because 4 Cologne teams ship with
 * team:null in the feed and only carry their name in the sticker title:
 *   1. team.tag (lowercased) === layout team.logo slug   (28 teams)
 *   2. normalized sticker-title team segment === normalized layout name (4 teams)
 *
 * Output is a committed fixture (same pattern as cologne-layout.json): ingested
 * once, not re-derived at runtime. The 18 MB source is never fetched by the app.
 *
 * Run:  node --experimental-strip-types scripts/build-logos.ts
 *   (or: npx tsx scripts/build-logos.ts)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const SOURCE_URL =
  "https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en/stickers.json";
const TOURNAMENT = "IEM Cologne 2026";

interface BymykelTeam {
  id: number;
  tag: string;
  name: string;
}
interface BymykelSticker {
  type: string;
  name: string;
  effect: string;
  image: string;
  tournament?: { id: number; name: string } | null;
  team?: BymykelTeam | null;
}
interface LayoutTeam {
  pickid: number;
  logo: string;
  name: string;
}

/** Normalize a team name/tag for fuzzy matching: lowercase, strip non-alphanumerics. */
function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** Pull the team segment out of "Sticker | <TEAM> | Cologne 2026". */
function teamFromTitle(name: string): string {
  const parts = name.split("|").map((p) => p.trim());
  return parts.length >= 2 ? parts[1] : "";
}

async function main() {
  const layout = JSON.parse(
    readFileSync(join(ROOT, "src/fixtures/cologne-layout.json"), "utf8"),
  ).result as { event: number; name: string; teams: LayoutTeam[] };

  process.stderr.write(`Fetching ${SOURCE_URL} …\n`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(
      `ByMykel fetch failed: ${res.status} ${res.statusText}. ` +
        `If this is a 404, the endpoint moved again — re-verify the base URL.`,
    );
  }
  const all = (await res.json()) as BymykelSticker[];

  // type:Team + the Cologne event + the plain paper variant (no Holo/Foil/Gold).
  const cologne = all.filter(
    (s) =>
      s.type === "Team" &&
      s.tournament?.name === TOURNAMENT &&
      s.effect === "Other",
  );
  process.stderr.write(
    `${all.length} stickers total → ${cologne.length} Team/Other for "${TOURNAMENT}".\n`,
  );

  // Build match indexes.
  const byTag = new Map<string, BymykelSticker>();
  const byName = new Map<string, BymykelSticker>();
  for (const s of cologne) {
    if (s.team?.tag) byTag.set(s.team.tag.toLowerCase(), s);
    const titleTeam = s.team?.name ?? teamFromTitle(s.name);
    if (titleTeam) byName.set(norm(titleTeam), s);
  }

  const logos: Record<string, unknown> = {};
  const unmatched: LayoutTeam[] = [];

  for (const t of layout.teams) {
    let sticker = byTag.get(t.logo.toLowerCase());
    let matchedBy: "tag" | "name" | null = sticker ? "tag" : null;
    if (!sticker) {
      sticker = byName.get(norm(t.name));
      if (sticker) matchedBy = "name";
    }
    if (!sticker) {
      unmatched.push(t);
      continue;
    }
    logos[String(t.pickid)] = {
      name: t.name,
      logo: t.logo,
      tag: sticker.team?.tag ?? null,
      image: sticker.image,
      effect: sticker.effect,
      matchedBy,
    };
  }

  const matched = Object.keys(logos).length;
  process.stderr.write(
    `Matched ${matched}/${layout.teams.length} layout teams ` +
      `(${unmatched.length} unmatched → self-host slug fallback).\n`,
  );
  if (unmatched.length) {
    process.stderr.write(
      "  Unmatched: " +
        unmatched.map((t) => `${t.name} (${t.logo})`).join(", ") +
        "\n",
    );
  }

  const manifest = {
    event: layout.event,
    eventName: layout.name,
    tournament: TOURNAMENT,
    source: "ByMykel/CSGO-API",
    sourceUrl: SOURCE_URL,
    generatedAt: new Date().toISOString(),
    note:
      "Generated by scripts/build-logos.ts. Primary logo source. Teams absent " +
      "here fall back to self-hosted /logos/<logo>.svg, then a monogram.",
    matched,
    unmatched: unmatched.map((t) => ({ pickid: t.pickid, name: t.name, logo: t.logo })),
    logos,
  };

  const out = join(ROOT, "src/fixtures/cologne-logos.json");
  writeFileSync(out, JSON.stringify(manifest, null, 2) + "\n");
  process.stderr.write(`Wrote ${out}\n`);
}

main().catch((err) => {
  process.stderr.write(`build-logos failed: ${err}\n`);
  process.exit(1);
});
